#%RAML 1.0 DataType
displayName: account
description: defines the account data type

type: object
properties:
  accountId?: string
  firstName: string
  lastName: string
  accounttype: string
  address: string
  postalcode: string
  country: string
  creationdate?: string
  miles: string

  
