#%RAML 1.0 NamedExample

value: 
-
  ID: "1"
  firstName: "tareke"
  lastName: "Ageze"
  accounttype: "personal"
  address: "12345 Green st,Boulder,colorado"
  postalcode: "82433"
  country: "USA"
  creationdate: 2015-12-04T13:00:00
  miles: string
-
  ID: "2"
  type: string
  requierd: true 
  firstName: "smith"
  lastName:  "Ageze"
  accounttype: "bussiness"
  address: "13415 Green st,Boulder,colorado"
  postalcode: "82430"
  country: "USA"
  creationdate: 2015-12-04T13:00:00
  miles: string